name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.29.2'

    - name: Install LLVM and Clang
      run: |
        choco install llvm --version=18.1.8 --allow-downgrade
        choco install mingw --version=12.2.0
        echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        # Verify lld is available
        lld --version
      shell: bash

    - name: Configure CMake with Clang
      run: |
        cmake -S . -B build -G "Ninja" `
        -DCMAKE_C_COMPILER=clang `
        -DCMAKE_CXX_COMPILER=clang++ `
        -DCMAKE_BUILD_TYPE=Release `
        -DCMAKE_VERBOSE_MAKEFILE=ON
      shell: pwsh

    - name: Build
      run: cmake --build build
      shell: pwsh

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
      shell: pwsh
