name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.29.2'

    - name: Install LLVM and Clang
      run: |
        choco install llvm --version=18.1.8 --allow-downgrade
        echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure CMake with Clang
      run: |
        cmake -S . -B build -G "Ninja" `
        -DCMAKE_C_COMPILER=clang `
        -DCMAKE_CXX_COMPILER=clang++ `
        -DCMAKE_BUILD_TYPE=Release
      shell: pwsh

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
