name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set up CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.29.2'

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DAX_BUILD_CONFIG=Development

    - name: Build
      run: cmake --build build

    - name: Run FoundationTests
      run: build\bin\FoundationTests.exe --gtest_output=xml:build\test-results\foundation.xml

    - name: Run AxEngineTests
      run: build\bin\AxEngineTests.exe --gtest_output=xml:build\test-results\engine.xml

    - name: Run AxLogTests
      run: build\bin\AxLogTests.exe --gtest_output=xml:build\test-results\log.xml

    - name: Run AxResourceTests
      run: build\bin\AxResourceTests.exe --gtest_output=xml:build\test-results\resource.xml
